
extern zend_class_entry *dgafka_bookstore_business_service_dto_command_book_removebookcommand_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Dto_Command_Book_RemoveBookCommand);

PHP_METHOD(Dgafka_BookStore_Business_Service_Dto_Command_Book_RemoveBookCommand, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_dto_command_book_removebookcommand___construct, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, guid, Dgafka\\BookStore\\Business\\Service\\Dto\\Command\\Book\\ValueObject\\Guid, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_business_service_dto_command_book_removebookcommand_method_entry) {
	PHP_ME(Dgafka_BookStore_Business_Service_Dto_Command_Book_RemoveBookCommand, __construct, arginfo_dgafka_bookstore_business_service_dto_command_book_removebookcommand___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
  PHP_FE_END
};
