
extern zend_class_entry *dgafka_bookstore_business_service_service_commandbus_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Service_CommandBus);

PHP_METHOD(Dgafka_BookStore_Business_Service_Service_CommandBus, execute);
PHP_METHOD(Dgafka_BookStore_Business_Service_Service_CommandBus, getCommandName);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_service_commandbus_execute, 0, 0, 2)
	ZEND_ARG_INFO(0, handler)
	ZEND_ARG_INFO(0, command)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_service_commandbus_getcommandname, 0, 0, 1)
	ZEND_ARG_INFO(0, command)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_business_service_service_commandbus_method_entry) {
	PHP_ME(Dgafka_BookStore_Business_Service_Service_CommandBus, execute, arginfo_dgafka_bookstore_business_service_service_commandbus_execute, ZEND_ACC_PUBLIC)
	PHP_ME(Dgafka_BookStore_Business_Service_Service_CommandBus, getCommandName, arginfo_dgafka_bookstore_business_service_service_commandbus_getcommandname, ZEND_ACC_PRIVATE)
  PHP_FE_END
};
