
extern zend_class_entry *dgafka_bookstore_business_service_repository_command_authorrepository_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Repository_Command_AuthorRepository);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_repository_command_authorrepository_save, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, author, Dgafka\\BookStore\\Business\\Model\\Entity\\Author, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_business_service_repository_command_authorrepository_method_entry) {
	PHP_ABSTRACT_ME(Dgafka_BookStore_Business_Service_Repository_Command_AuthorRepository, save, arginfo_dgafka_bookstore_business_service_repository_command_authorrepository_save)
  PHP_FE_END
};
