
extern zend_class_entry *dgafka_bookstore_business_service_repository_command_bookrepository_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Repository_Command_BookRepository);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_save, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, book, Dgafka\\BookStore\\Business\\Model\\Entity\\Book, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_remove, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, book, Dgafka\\BookStore\\Business\\Model\\Entity\\Book, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_findbyid, 0, 0, 1)
	ZEND_ARG_INFO(0, id)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_business_service_repository_command_bookrepository_method_entry) {
	PHP_ABSTRACT_ME(Dgafka_BookStore_Business_Service_Repository_Command_BookRepository, save, arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_save)
	PHP_ABSTRACT_ME(Dgafka_BookStore_Business_Service_Repository_Command_BookRepository, remove, arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_remove)
	PHP_ABSTRACT_ME(Dgafka_BookStore_Business_Service_Repository_Command_BookRepository, findById, arginfo_dgafka_bookstore_business_service_repository_command_bookrepository_findbyid)
  PHP_FE_END
};
