
extern zend_class_entry *dgafka_bookstore_business_service_handler_exception_dependencyinjectionexception_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Handler_Exception_DependencyInjectionException);

