
extern zend_class_entry *dgafka_bookstore_application_inmemory_repository_command_bookrepository_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository);

PHP_METHOD(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, __construct);
PHP_METHOD(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, save);
PHP_METHOD(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, remove);
PHP_METHOD(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, findById);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_save, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, book, Dgafka\\BookStore\\Business\\Model\\Entity\\Book, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_remove, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, book, Dgafka\\BookStore\\Business\\Model\\Entity\\Book, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_findbyid, 0, 0, 1)
	ZEND_ARG_INFO(0, id)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_application_inmemory_repository_command_bookrepository_method_entry) {
	PHP_ME(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, __construct, NULL, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, save, arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_save, ZEND_ACC_PUBLIC)
	PHP_ME(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, remove, arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_remove, ZEND_ACC_PUBLIC)
	PHP_ME(Dgafka_BookStore_Application_InMemory_Repository_Command_BookRepository, findById, arginfo_dgafka_bookstore_application_inmemory_repository_command_bookrepository_findbyid, ZEND_ACC_PUBLIC)
  PHP_FE_END
};
