
extern zend_class_entry *dgafka_bookstore_business_service_dto_command_author_createauthorcommand_ce;

ZEPHIR_INIT_CLASS(Dgafka_BookStore_Business_Service_Dto_Command_Author_CreateAuthorCommand);

PHP_METHOD(Dgafka_BookStore_Business_Service_Dto_Command_Author_CreateAuthorCommand, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dgafka_bookstore_business_service_dto_command_author_createauthorcommand___construct, 0, 0, 3)
	ZEND_ARG_OBJ_INFO(0, guid, Dgafka\\BookStore\\Business\\Model\\ValueObject\\Guid, 0)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, surname)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dgafka_bookstore_business_service_dto_command_author_createauthorcommand_method_entry) {
	PHP_ME(Dgafka_BookStore_Business_Service_Dto_Command_Author_CreateAuthorCommand, __construct, arginfo_dgafka_bookstore_business_service_dto_command_author_createauthorcommand___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
  PHP_FE_END
};
